/**
 * @author uAtomicBoolean
 * @description
 *      Simple 'ping' command answering 'Pong !' when executed.
 */

import { CommandInteraction, SlashCommandBuilder } from 'discord.js';


export const data = new SlashCommandBuilder()
	.setName('ping')
	.setDescription('[misc] Pong !');


/**
 * The command's handler.
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
export async function execute(interaction: CommandInteraction) {
	await interaction.reply('Pong !');
}