/**
 * @author uAtomicBoolean
 * @description
 *      Simple 'ping' command answering 'Pong !' when executed.
 */

import { CommandInteraction, SlashCommandBuilder } from 'discord.js';


/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
export const slashCommand = new SlashCommandBuilder()
	.setName('ping')
	.setDescription('[misc] Pong !');


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * The command's handler.
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
export async function execute(interaction: CommandInteraction) {
	await interaction.reply('Pong !');
}
