/**
 * @author uAtomicBoolean
 * @description
 *      Simple 'ping' command answering 'Pong !' when executed.
 */

const { CommandInteraction, SlashCommandBuilder } = require('discord.js');


/* ----------------------------------------------- */
/* COMMAND BUILD                                   */
/* ----------------------------------------------- */
const slashCommand = new SlashCommandBuilder()
	.setName('ping')
	.setDescription('[misc] Pong !');


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * The command's handler.
 * @param {CommandInteraction} interaction The interaction generated by the command's execution.
 */
async function execute(interaction) {
	await interaction.reply('Pong !');
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	execute,
};
